services:
  app:
    container_name: ganglem-ropagen
    image: ganglem/ropagen:latest
    env_file:
      - .env
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ganglem-ropagen.rule=Host(`ropagen.eu`)
      - traefik.http.routers.ganglem-ropagen.entrypoints=websecure
      - traefik.http.routers.ganglem-ropagen.tls=true
      - traefik.http.routers.ganglem-ropagen.tls.certresolver=le-emilija
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true

  dev:
    container_name: ganglem-ropagen-dev
    image: ganglem/ropagen-dev:latest
    env_file:
      - .env
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ganglem-ropagen-dev.rule=Host(`dev.ropagen.eu`)
      - traefik.http.routers.ganglem-ropagen-dev.entrypoints=websecure
      - traefik.http.routers.ganglem-ropagen-dev.tls=true
      - traefik.http.routers.ganglem-ropagen-dev.tls.certresolver=le-emilija
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true


networks:
  web:
    external: true
